# PERFIL DE CONEXION: H2 IN-MEMORY (ALTERNATICO SIN SERVIDOR MYSQL)
spring.datasource.url=jdbc:h2:mem:db_productos;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.sql.init.schema-locations=classpath:db/schema_and_procedures_h2.sql
spring.sql.init.mode=always
